name: CI/CD with PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
  workflow_run:
    workflows: ["PHPUnit Tests"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests/

  notify_discord:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMITTER: ${{ github.event.head_commit.committer.name }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"PHPUnit Tests on Main branch completed successfully!\n\nCommit: $COMMIT_SHA\nMessage: $COMMIT_MESSAGE\nCommitter: $COMMITTER\nAuthor: $AUTHOR\"}" \
          $WEBHOOK_URL
