name: CI/CD with PHPUnit

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["PHPUnit Tests"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests/

  notify_discord:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          if [ "$BRANCH" == "main" ]; then
            COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
            COMMITTER=$(git log --format=%an -n 1 ${{ github.sha }})
            AUTHOR=$(git log --format=%ae -n 1 ${{ github.sha }})
            TARGET_BRANCH="main"
            SOURCE_BRANCH="development"
          fi

          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Merged pull request changes from $SOURCE_BRANCH to $TARGET_BRANCH branch.\n\nCommit: $COMMIT_SHA\nMessage: $COMMIT_MESSAGE\nCommitter: $COMMITTER\nAuthor: $AUTHOR\"}" \
          $WEBHOOK_URL
