name: CI/CD with PHPUnit

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["PHPUnit Tests"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests/

  notify_discord:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMITTER: ${{ github.event.head_commit.committer.name }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
          BRANCH: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.ref }}
        run: |
          if [ "$BRANCH" == "refs/pull/${{ github.event.pull_request.number }}/merge" ]; then
            COMMIT_SHA=$(git log --format=%H -n 1 ${{ github.event.before }})
            COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.before }})
            COMMITTER=$(git log --format=%an -n 1 ${{ github.event.before }})
            AUTHOR=$(git log --format=%ae -n 1 ${{ github.event.before }})
          fi

          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"PHPUnit Tests on $BRANCH branch completed successfully!\n\nCommit: $COMMIT_SHA\n"}" \
          $WEBHOOK_URL
